analytics: {}
color:
  brandColors:
    - '#c5c0a3'
    - '#5e5943'
    - '#7ba69c'
    - '#222b48'
    - '#ffffcf'
  brandStrength: 0
  lightness: 0.205416
  rhythmicContrast: 0.39832
  saturation: 0.494402
cta: {}
layout_spectrum: 0.29918011859990656
name: Brasstown Morris
opengraph: {}
purpose: []
typography_spectrum: 0.51012
