name: Brasstown Morris
favicon: null
layout_spectrum: 0.29918011859990656
typography_spectrum: 0.51012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5c0a3'
    - '#5e5943'
    - '#7ba69c'
    - '#222b48'
    - '#ffffcf'
  brandStrength: 0.5
  lightness: 0.20541652338579297
  saturation: 0.7589531689882278
  rhythmicContrast: 0.1980493573937565
purpose: []
